<a href="https://colab.research.google.com/github/Haldar18/Intership/blob/main/TensorFlow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.4

ERROR: Could not find a version that satisfies the requirement tensorflow==1.4 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.14.0rc0, 2.14.0rc1)
ERROR: No matching distribution found for tensorflow==1.4


In [2]:
import tensorflow as tf

In [5]:
tf.__version__


'2.13.0'

In [6]:
# to define a constant
hello_constant =tf.constant('Hello World!!')
hello_constant

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World!!'>

In [10]:
#Create tensorflow object called tensor

with tf.compat.v1.Session() as sess:
  hello_constant =tf.constant('Hello World!!')
  #Run the constant operation in the session
  output=sess.run(hello_constant)
  print(output)

b'Hello World!!'


In [12]:
#Tensor

with tf.Graph().as_default():
  c1=tf.constant(4,dtype=tf.float64,name='c')
  c2=tf.constant(4,dtype=tf.int32,name='c')
  c3=tf.constant(4,dtype=tf.int32,name='c')
  print(c1.name)
  print(c2.name)
  print(c3.name)

c:0
c_1:0
c_2:0


In [22]:
tf.compat.v1.disable_eager_execution()

ValueError: ignored

In [20]:
# Grouping under the same place
with tf.Graph().as_default():
  c1=tf.constant(4,dtype=tf.float64,name='c')
with tf.name_scope("Prefix_name"):
  c2=tf.constant(4,dtype=tf.int32,name='c')
  c3=tf.constant(4,dtype=tf.int32,name='c')
  print(c2.name)
  print(c3.name)
print(c1.name)


Prefix_name/c:0
Prefix_name/c_1:0
c:0


In [23]:
c=tf.constant([[123,456,789],[222,333,444]])
sess=tf.compat.v1.Session()
sess.run(c)

array([[123, 456, 789],
       [222, 333, 444]], dtype=int32)

In [9]:
#Variables

with tf.compat.v1.Session() as sess :
  int_val=tf.random.normal((1,5),0,1)
  var=tf.Variable(int_val,name='var')
  print('pre_run:\n{}'.format(var))
  init=tf.compat.v1.global_variables_initializer()
  sess.run(init)
  post_var=sess.run(var)

print("\n post run:\n{}".format(post_var))

pre_run:
<tf.Variable 'var_3:0' shape=(1, 5) dtype=float32>

 post run:
[[ 0.5435019  0.694639   1.2012894 -1.1109173 -0.9465337]]


In [14]:
#e TensorFlow Input
x=tf.compat.v1.placeholder(tf.string)
with tf.compat.v1.Session() as sess:
  output=sess.run(x,feed_dict={x:'test'})
  print(output)

test


In [15]:
tf.compat.v1.disable_eager_execution()

In [17]:
import tensorflow.compat.v1 as tf
# more than 1 variable
x=tf.placeholder(tf.string)
y=tf.placeholder(tf.int32)
z=tf.placeholder(tf.float32)
with tf.Session() as sess :
  output_x=sess.run(x,feed_dict={x:'Test String',y:123,z:34.3})
  output_y=sess.run(y,feed_dict={y:234})
print(output_x)
print(output_y)

Test String
234


In [21]:
x=tf.placeholder('float',None)
y=x*2
with tf.Session() as sess :
  result=sess.run(y,feed_dict={x:[123]})
print(result)

[246.]
